// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_PcGn0Z1t6LvHPNYqzilqhthJWdKgUlA',
    appId: '1:218691982421:web:e093a28ce92d08aa4330dc',
    messagingSenderId: '218691982421',
    projectId: 'fitnut2',
    authDomain: 'fitnut2.firebaseapp.com',
    storageBucket: 'fitnut2.appspot.com',
    measurementId: 'G-0QRL34WF69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCDtJlzicOp-w0ZXx0H5BRTAZuNi5kHzs',
    appId: '1:218691982421:android:aec8cab76e1018be4330dc',
    messagingSenderId: '218691982421',
    projectId: 'fitnut2',
    storageBucket: 'fitnut2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtMhDV7Hz0H_CXwu1qwSD7HijJ2sgMD9s',
    appId: '1:218691982421:ios:79afd3bdd70b23e64330dc',
    messagingSenderId: '218691982421',
    projectId: 'fitnut2',
    storageBucket: 'fitnut2.appspot.com',
    iosClientId: '218691982421-dco3a3dodtlng1c55hh4ko0igc1dht8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtMhDV7Hz0H_CXwu1qwSD7HijJ2sgMD9s',
    appId: '1:218691982421:ios:79afd3bdd70b23e64330dc',
    messagingSenderId: '218691982421',
    projectId: 'fitnut2',
    storageBucket: 'fitnut2.appspot.com',
    iosClientId: '218691982421-dco3a3dodtlng1c55hh4ko0igc1dht8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnut',
  );
}
